export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const DASHBOARD_REPORT_SUCCESS = "DASHBOARD_REPORT_SUCCESS";
export const DASHBOARD_REPORT_FALIURE = "DASHBOARD_REPORT_FALIURE";
export const CHART_DATA_SUCCESS = "CHART_DATA_SUCCESS";
export const CHART_DATA_FALIURE = "CHART_DATA_FALIURE";

export const DASHBOARD_FAILURE = "DASHBOARD_FAILURE";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";

export const RATION_SUCCESS = "RATION_SUCCESS";
export const RATION_FALIURE = "RATION_FALIURE";

export const GENDER_SUCCESS = "GENDER_SUCCESS";
export const GENDER_FALIURE = "GENDER_FALIURE";

export const ECONOMIC_CATEGORIES_SUCCESS = "ECONOMIC_CATEGORIES_SUCCESS";
export const ECONOMIC_CATEGORIES_FALIURE = "ECONOMIC_CATEGORIES_FALIURE";

export const RESIDENTIAL_SUCCESS = "RESIDENTIAL_SUCCESS";
export const RESIDENTIAL_FALIURE = "RESIDENTIAL_FALIURE";

export const RELATION_SUCCESS = "RELATION_SUCCESS";
export const RELATION_FALIURE = "RELATION_FALIURE";

export const QUALIFICATION_SUCCESS = "QUALIFICATION_SUCCESS";
export const QUALIFICATION_FALIURE = "QUALIFICATION_FALIURE";

export const OCCUPATION_SUCCESS = "OCCUPATION_SUCCESS";
export const OCCUPATION_FALIURE = "OCCUPATION_FALIURE";

export const SET_VALUE = "SET_VALUE";
export const SET_VALUE_ERROR = "SET_VALUE_ERROR";

export const RELIGION_SUCCESS = "RELIGION_SUCCESS";
export const RELIGION_FALIURE = "RELIGION_FALIURE";

export const SOCIAL_CAT_SUCCESS = "SOCIAL_CAT_SUCCESS";
export const SOCIAL_CAT_FALIURE = "SOCIAL_CAT_FALIURE";

export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FALIURE = "DISTRICT_FALIURE";
export const TEHSIL_SUCCESS = "TEHSIL_SUCCESS";
export const TEHSIL_FALIURE = "TEHSIL_FALIURE";
export const PATWAR_SUCCESS = "PATWAR_SUCCESS";
export const PATWAR_FALIURE = "PATWAR_FALIURE";
export const DIVISION_SUCCESS = "DIVISION_SUCCESS";
export const DIVISION_FALIURE = "DIVISION_FALIURE";
export const SUB_DIVISION_SUCCESS = "SUB_DIVISION_SUCCESS";
export const SUB_DIVISION_FALIURE = "SUB_DIVISION_FALIURE";

export const MUNICIPALITY_SUCCESS = "MUNICIPALITY_SUCCESS";
export const MUNICIPALITY_FALIURE = "MUNICIPALITY_FALIURE";
export const PANCHAYAT_SUCCESS = "PANCHAYAT_SUCCESS";
export const PANCHAYAT_FALIURE = "PANCHAYAT_FALIURE";
export const BLOCK_SUCCESS = "BLOCK_SUCCESS";
export const BLOCK_FALIURE = "BLOCK_FALIURE";

export const WARD_SUCCESS = "WARD_SUCCESS";
export const WARD_FALIURE = "WARD_FALIURE";
export const VILLAGE_SUCCESS = "VILLAGE_SUCCESS";
export const VILLAGE_FALIURE = "VILLAGE_FALIURE";

export const FAMILY_DETAIL_SUCCESS = "FAMILY_DETAIL_SUCCESS";
export const FAMILY_DETAIL_FALIURE = "FAMILY_DETAIL_FALIURE";

export const FAMILIES_LIST_SUCCESS = "FAMILIES_LIST_SUCCESS";
export const FAMILIES_LIST_FALIURE = "FAMILIES_LIST_FALIURE";
export const HOTELS_LIST_SUCCESS = "HOTELS_LIST_SUCCESS";
export const HOTELS_LIST_FALIURE = "HOTELS_LIST_FALIURE";

export const FAMILIES_DETAIL_SUCCESS = "FAMILIES_DETAIL_SUCCESS";
export const FAMILIES_DETAIL_FALIURE = "FAMILIES_DETAIL_FALIURE";
export const HOTEL_DETAIL_SUCCESS = "HOTEL_DETAIL_SUCCESS";
export const HOTEL_DETAIL_FALIURE = "HOTEL_DETAIL_FALIURE";
export const GET_RATION_FAMILY_SUCCESS = "GET_RATION_FAMILY_SUCCESS";
export const GET_RATION_FAMILY_FALIURE = "GET_RATION_FAMILY_FALIURE";

export const SHOW_LOADER_SUCCESS = "SHOW_LOADER_SUCCESS";
export const SHOW_LOADER_FALIURE = "SHOW_LOADER_FALIURE";

export const ON_ROLES_SUCCESS = "ON_ROLES_SUCCESS";
export const ON_ROLES_FALIURE = "ON_ROLES_FALIURE";

export const ON_ROLES_DETAILS_SUCCESS = "ON_ROLES_DETAILS_SUCCESS";
export const ON_ROLES_DETAILS_FALIURE = "ON_ROLES_DETAILS_FALIURE";

export const ON_ROLES_UPDATE_SUCCESS = "ON_ROLES_UPDATE_SUCCESS";
export const ON_ROLES_UPDATE_FALIURE = "ON_ROLES_UPDATE_FALIURE";

export const ON_ROLES_CREATE_SUCCESS = "ON_ROLES_CREATE_SUCCESS";
export const ON_ROLES_CREATE_FALIURE = "ON_ROLES_CREATE_FALIURE";

export const SUMMARY_REPORT_SUCCESS = "SUMMARY_REPORT_SUCCESS";
export const SUMMARY_REPORT_FALIURE = "SUMMARY_REPORT_SUCCESS";
export const CONSUMER_SUMMARY_REPORT_SUCCESS = "CONSUMER_SUMMARY_REPORT_SUCCESS";
export const CONSUMER_SUMMARY_REPORT_FALIURE = "CONSUMER_SUMMARY_REPORT_SUCCESS";

export const REGECTION_REASONS_SUCCESS = "REGECTION_REASONS_SUCCESS";
export const REGECTION_REASONS_FAILIURE = "REGECTION_REASONS_FAILIURE";

export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FALIURE = "VERIFICATION_FALIURE";

export const UPDATE_FAMILY_SUCCESS = "UPDATE_FAMILY_SUCCESS";
export const UPDATE_FAMILY_FALIURE = "UPDATE_FAMILY_FALIURE";

export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FALIURE = "UPDATE_MEMBER_FALIURE";

export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FALIURE = "UPDATE_PROPERTY_FALIURE";

export const CSC_SURVEY_REPORT_SUCCESS = "CSC_SURVEY_REPORT_SUCCESS";
export const CSC_SURVEY_REPORT_FAILURE = "CSC_SURVEY_REPORT_FAILURE";

export const CSCUSER_SUCCESS = "CSCUSER_SUCCESS";
export const CSCUSER_FAILURE = "CSCUSER_FAILURE";

export const CSC_REPORT_DOWNLOAD_SUCCESS = "CSC_REPORT_DOWNLOAD_SUCCESS";
export const CSC_REPORT_DOWNLOAD_FALIURE = "CSC_REPORT_DOWNLOAD_FALIURE";

export const CONSUMER_REPORT_DOWNLOAD_SUCCESS = "CONSUMER_REPORT_DOWNLOAD_SUCCESS";
export const CONSUMER_REPORT_DOWNLOAD_FALIURE = "CONSUMER_REPORT_DOWNLOAD_FALIURE";
export const DATA_DOWNLOAD_SUCCESS = "DATA_DOWNLOAD_SUCCESS";
export const DATA_DOWNLOAD_FALIURE = "DATA_DOWNLOAD_FALIURE";
